# Generated by Django 2.2.3 on 2019-07-21 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
