# Generated by Django 2.2.3 on 2019-07-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_course_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('content_type', models.CharField(choices=[('pdf', 'PDF'), ('youtube', 'YouTube Video'), ('image', 'Image')], max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='contents',
            field=models.ManyToManyField(to='classroom.Content'),
        ),
    ]
