# Generated by Django 2.2.3 on 2019-07-22 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_course_recommended'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('video_id', models.CharField(max_length=16)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classroom.Content')),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('url', models.URLField()),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classroom.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('url', models.URLField()),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classroom.Content')),
            ],
        ),
    ]
